title:
  en: Layout
  de: Layout
options:
  changeTemplate:
    - text
    - article
    - default

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          extends: fields/pageTitle
          layout:
            type: layout
            layouts:
              - "1/2, 1/2"
              - "1/1"
            label:
              de: Inhalt
              en: Content
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
      files:
        type: files

