title: Dashboard

tabs:

# Seiten Tab
  general:
    label:
      de: Seiten
      en: Pages
    icon: page
    sections:
      pages:
        type: pages
        layout: list
      fields:
        fields:
          externalLinksList: fields/externalLinksList

# Open Graph Tab
  openGraph: tabs/OpenGraph

# Browser-Styling Tab
  iconAndTheme: tabs/iconAndTheme

# Catch-All Files
  catchAllFiles:
    label:
      de: Dateien
      en: Files
    icon: file
    sections:
      catchAllfiles:
        type: files
        help:
          de: |
            Hier werden alle Dateien angezeigt, die keiner spezifischen Seite zugeordnet sind. Diese Dateien werden wahrscheinlich für Open graph, Favikonen und ähliches genutzt.
          en: |
            This section displays all files that are not assigned to a specific page. These files are probably used for Open Graph, favicons and the like.
