title: Dashboard

tabs:

# Seiten Tab
  general:
    label:
      de: Seiten
      en: Pages
    sections:
      pages:
        type: pages
        layout: list
      fields:
        fields:
          externalLinksList: fields/externalLinksList

# Open Graph Tab
  openGraph: tabs/OpenGraph

# Browser-Styling Tab
  iconAndTheme: tabs/iconAndTheme
